/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Assert;
import org.junit.Test;
import org.junit.jupiter.api.DisplayName;

public class AppTest {

    @Test
    @DisplayName("given message when execute mobile call function then return right message")
    public void testMobileCall() {
        Mobile mobile = new Mobile("P30", "green", "HuaWei");

        String message = mobile.call("Hello Jelly");

        Assert.assertEquals(message, "Message: Hello Jelly");
    }

    @Test
    @DisplayName("given message when execute IPhone call function  then return right message")
    public void testIPhoneCall() {
        Mobile mobile = new IPhone("iPhoneX", "green", "iPhone");

        String message = mobile.call("Hello Jelly");

        Assert.assertEquals(message, "<iPhone>Message: Hello Jelly");
    }

    @Test
    @DisplayName("given message when execute AndroidMobile call function  then return right message")
    public void testAndroidMobileCall() {
        Mobile mobile = new AndroidMobile("P30", "green", "HuaWei");

        String message = mobile.call("Hello Jelly");

        Assert.assertEquals(message, "<Android>Message: Hello Jelly");
    }

    @Test
    @DisplayName("when execute getInformation function then return right message")
    public void testGetInformation() {
        Mobile mobile = new Mobile("P30", "green", "HuaWei");
        String information = mobile.getInformation();

        Assert.assertEquals(information, "name: P30, color: green, brand: HuaWei");
    }
}
