/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Assert;
import org.junit.Test;
import org.junit.jupiter.api.DisplayName;

public class AppTest {

    @Test
    @DisplayName("given message when execute mobile call function then return right message")
    public void testMobileCall() {
        Mobile mobile = new Mobile("P30", "green", "HuaWei");

        String message = mobile.call("Hello Tom");

        Assert.assertEquals(message, "Message: Hello Tom");
    }

    @Test
    @DisplayName("given message when execute IPhone call function  then return right message")
    public void testIPhoneCall() {
        Mobile mobile = new IPhone("iPhoneX", "green", "iPhone");

        String message = mobile.call("Hello Jelly");

        Assert.assertEquals(message, "<iPhone>Message: Hello Jelly");
    }

    @Test
    @DisplayName("given message when execute AndroidMobile call function  then return right message")
    public void testAndroidMobileCall() {
        Mobile mobile = new AndroidMobile("P30", "green", "HuaWei");

        String message = mobile.call("Hello Jelly");

        Assert.assertEquals(message, "<Android>Message: Hello Jelly");
    }

    @Test
    @DisplayName("when execute getInformation function then return right message")
    public void testGetInformation() {
        Mobile mobile = new Mobile("P30", "green", "HuaWei");
        String information = mobile.getInformation();

        Assert.assertEquals(information, "name: P30, color: green, brand: HuaWei");
    }

    @Test
    @DisplayName("given message that length great then 10, when person call with iPhone then output right message")
    public void testIPhoneLimitMessageLength() {
        Mobile mobile = new IPhone("iPhoneX", "green", "iPhone");

        String message = mobile.call("I want to watch movies");

        Assert.assertEquals(message, "<iPhone> Message cannot be sent");
    }

    @Test
    @DisplayName("given message that length great then 10, when person call with Android then output right message")
    public void testAndroidMobileLimitMessageLength() {
        Mobile mobile = new AndroidMobile("P30", "green", "HuaWei");

        String message = mobile.call("I want to watch movies");

        Assert.assertEquals(message, "<Android> Message cannot be sent");
    }

    @Test
    @DisplayName("given iPhone to person when it call then output right message.")
    public void testPersonCallWithIPhone() {
        Mobile mobile = new IPhone("iPhoneX", "green", "iPhone");
        Person person = new Person("Katty", mobile);
        String message = person.call("Hello Tom");
        Assert.assertEquals(message, "<iPhone>Message: Hello Tom");

        person.changeMobile(new AndroidMobile("P30", "green", "HuaWei"));
        message = person.call("Hello Tom");
        Assert.assertEquals(message, "<Android>Message: Hello Tom");

    }
}
